
-- Cria a tabela Usuario
CREATE TABLE tb_usuario(
ID INTEGER PRIMARY KEY, 
NOME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SENHA VARCHAR(50) NOT NULL,
CONSTRAINT UQ_EMAIL_USUARIO UNIQUE (NOME)
   
);

-- Inserindo dados na tabela Usuario
INSERT INTO tb_usuario (ID, NOME, EMAIL, SENHA) VALUES (1,'João Silva', 'joaosilva@teste.com.br', 'silva1289');
INSERT INTO tb_usuario (ID, NOME, EMAIL, SENHA) VALUES (2,'Maria Silva', 'silvamaria@teste.com.br', 'smaria4569');
INSERT INTO tb_usuario (ID, NOME, EMAIL, SENHA) VALUES (3,'Claudia Souza', 'claudiasouza@teste.com.br', 'csouza5487');
INSERT INTO tb_usuario (ID, NOME, EMAIL, SENHA) VALUES (4,'Jurema Andrade', 'juremaandrade@teste.com.br', 'andradej5679');


-- Cria a tabela Categoria
CREATE TABLE tb_categorias(
ID INTEGER PRIMARY KEY,
TIPO VARCHAR(255) NOT NULL,
CONSTRAINT UQ_NOME_CATEGORIA UNIQUE (TIPO)

);

-- Insere os dados na tabela categoria
INSERT INTO tb_categorias (ID, TIPO) VALUES (1, 'BEBIDA ALCOOLICA');
INSERT INTO tb_categorias (ID, TIPO) VALUES (2, 'BEBIDA NÃO ALCOOLICA');
INSERT INTO tb_categorias (ID, TIPO) VALUES (3, 'SNACKS');
INSERT INTO tb_categorias (ID, TIPO) VALUES (4, 'DIVERSOS');

--Cria a tabela Pedidos

CREATE TABLE tb_pedidos(
ID INTEGER PRIMARY KEY,
ID_USUARIO int NOT NULL,
ENDERECO VARCHAR(255) NOT NULL,
QUANTIDADE int NOT NULL,
PRECO_TOTAL DECIMAL(4,2),
DATA_ELABORACAO DATE,
FOREIGN KEY (ID_USUARIO) REFERENCES tb_usuario(ID)
);

-- Insere os dados na tabela Pedidos
INSERT INTO tb_pedidos (ID, ID_USUARIO, ENDERECO, QUANTIDADE, PRECO_TOTAL, DATA_ELABORACAO) 
VALUES (301, 1,'RUA DOZE 567',10, 56,'22-03-2020');

INSERT INTO tb_pedidos (ID, ID_USUARIO, ENDERECO, QUANTIDADE, PRECO_TOTAL, DATA_ELABORACAO) 
VALUES (302, 2, 'RUA DOLORES 75', 2, 8.40,'01-04-2021');

INSERT INTO tb_pedidos (ID, ID_USUARIO, ENDERECO, QUANTIDADE, PRECO_TOTAL, DATA_ELABORACAO) 
VALUES (303, 3, 'RUA SETEMBRO 482', 5, 17.50,'04-03-2022');

INSERT INTO tb_pedidos (ID, ID_USUARIO, ENDERECO, QUANTIDADE, PRECO_TOTAL, DATA_ELABORACAO) 
VALUES (304, 4, 'RUA OLIVEIRA 36', 2, 40,'06-10-1999');

--Cria a tabela Produtos

CREATE TABLE tb_produtos(
ID NUMBER(4) PRIMARY KEY,
ID_PEDIDO NUMBER(4),
ID_CATEGORIA NUMBER(4),
NOME VARCHAR(50) NOT NULL,
PRECO NUMBER(4,2),
FOREIGN KEY (ID_PEDIDO) REFERENCES tb_pedidos(ID),
FOREIGN KEY (ID_CATEGORIA) REFERENCES tb_categorias(ID),
CONSTRAINT UQ_NOME_PRODUTO UNIQUE (NOME)
);

-- Insere os dados na tabela Produtos
INSERT INTO tb_produtos (ID, ID_PEDIDO, ID_CATEGORIA, NOME, PRECO) VALUES (1, 301, 01, 'CERVEJA BRAHMA', 5.60);
INSERT INTO tb_produtos (ID, ID_PEDIDO, ID_CATEGORIA, NOME, PRECO) VALUES (2, 302, 02, 'SUCO', 4.20);
INSERT INTO tb_produtos (ID, ID_PEDIDO, ID_CATEGORIA, NOME, PRECO) VALUES (3, 303, 03, 'SALGADINHO', 3.50);
INSERT INTO tb_produtos (ID, ID_PEDIDO, ID_CATEGORIA, NOME, PRECO) VALUES (4, 304, 04, 'GELO', 20.00);